import Head from "next/head";
import Image from "next/image";
import claudio from "../public/Claudio.jpeg";
import styles from "../styles/Home.module.css";
import * as React from "react";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import { styled } from "@mui/material/styles";

export default function Home() {
  const [secret, setSecret] = React.useState("");
  const secretKey = "claudio";
  const indizio = process.env.NEXT_PUBLIC_INDIZIO;
  console.log(secretKey, indizio);

  const SubmitButton = styled(Button)({
    backgroundColor: "#f29f05",
    "&:hover": {
      backgroundColor: "#f29f05",
    },
    "&:focus": {
      backgroundColor: "#f29f05",
    },
    "&:active": {
      backgroundColor: "#f29f05",
    },
  });

  const Welcome = () => (
    <Box
      sx={{
        display: "flex",
        flexDirection: "column",
        backgroundColor: "#400d01",
        mt: 3,
        p: 3,
        textAlign: " center",
        justifyContent: "space-between",
        height: "100%",
      }}
    >
      <Typography variant="h3" color="#f29f05">
        Escape Carbognano!
      </Typography>
      <Paper
        sx={{
          backgroundColor: "#a62f03",
          ml: 2,
          mr: 2,
          mb: 2,
        }}
        elevation={4}
      >
        <Typography variant="h6" color="#f29f05" mt={4} p={2}>
          Dimostrate di essere veramente degni di proseguire le vostre indagini!
        </Typography>
        <Typography variant="h6" color="#f29f05" p={2} pt={0}>
          Orsù ditemi, chi è il più bell&apos;accolito di tutta la diocesi?
        </Typography>
        <Box
          component="form"
          onSubmit={(ev) => {
            const data = new FormData(ev.currentTarget);
            const input = data.get("secretInput").trim().toLowerCase();
            setSecret(input);
          }}
          noValidate
          m={2}
          sx={{
            display: "flex",
            flexDirection: "row",
            gap: "20px",
          }}
        >
          <TextField
            variant="filled"
            id="secretInput"
            name="secretInput"
            sx={{
              flex: 10,
            }}
          ></TextField>
          <SubmitButton type="submit" variant="contained" sx={{ flex: 2 }}>
            OK
          </SubmitButton>
        </Box>
      </Paper>
    </Box>
  );
  const SecretOk = () => (
    <Box
      sx={{
        display: "flex",
        flexDirection: "column",
        padding: 3,
        margin: 3,
        textAlign: "center",
        height: "100%",
        justifyContent: "space-between",
      }}
    >
      <Image src={claudio} alt="Mitico" width={300} />

      <Typography variant="h4" color="#f29f05">
        Risposta corretta!
      </Typography>
      <Typography variant="h6" color="#f29f05">
        {indizio}
      </Typography>
    </Box>
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Escape Carbognano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {secret !== secretKey ? <Welcome /> : <SecretOk />}
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

        {/* <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
